image: node:alpine
cache:
  paths:
    - node_modules/

build_production:
  stage: build
  environment: Production  
  only:
    - master
  script:
    - npm install
    # - npm i -g firebase-tools
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - build

test_production:
  stage: test
  environment: Production  
  only:
    - master
  script:
    - npm run test:unit

deploy_production:
  stage: deploy
  environment: Production  
  only:
    - master
  before_script:
    - npm i -g firebase-tools
    - (if [ -d "build" ]; then echo ok; else exit "no build folder, try to run pipeline again"; fi)
  script:
    # - npm install
    # - npm i -g firebase-tools
    # - npm run build
    - firebase deploy --non-interactive --token ${FIREBASE_TOKEN}