image: node:alpine
cache:
  paths:
    - node_modules/

build_production:
  stage: build
  environment: Production  
  only:
    - master
  script:
    - npm install
    - npm run build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - build
      
unit_test_production:
  stage: test
  environment: Production  
  only:
    - master
  script:
    - npm run test:unit

e2e_test_production:
  stage: test
  environment: Production
  only:
    - master
  script:
    - npm run test:e2e
  artifacts:
    name: "e2e_artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - e2e_artifacts

deploy_production:
  stage: deploy
  environment: Production  
  only:
    - master
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase deploy --non-interactive --token ${FIREBASE_TOKEN}
  when: manual